<template>
	<view class="compound-page">
		<view class="status-bar" :style="{ height: statusBarHeight + 'px' }"></view>
		<view class="page-shell">
			<view class="topbar">
				<button class="round-button" aria-label="返回" @tap="goBack">‹</button>
				<view class="topbar-copy"><text class="topbar-kicker">COMPOUND SYSTEM</text><text class="topbar-title">复利系统</text></view>
				<button class="round-button add-button" aria-label="发现新的复利项" :disabled="home.portfolio.activeCount >= 3" @tap="openNewPlan">+</button>
			</view>

			<view v-if="loading" class="state-card"><view class="loading-dot"></view><text>正在读取复利机会地图</text></view>
			<view v-else-if="loadError" class="state-card error"><text>复利系统暂时没有读到</text><button class="dark-pill" @tap="loadAll">重新读取</button></view>

			<template v-else>
				<view class="portfolio-hero" :class="{ empty: !home.plans.length }">
					<text class="eyebrow">{{ home.plans.length ? weekRange : '找到适合自己的长期积累' }}</text>
					<text v-if="home.plans.length" class="portfolio-title">今天，只推进最重要的一步</text>
					<text v-else class="portfolio-title">选择一件值得长期积累的事</text>
					<text class="portfolio-copy">{{ home.plans.length ? '先看现在该做什么；完整计划和进度需要时再展开。' : '不必先懂术语。选一个方向，菇会带你一步步建立自己的计划。' }}</text>
					<view v-if="home.plans.length" class="hero-status"><text>{{ home.portfolio.activeCount }} 项进行中</text><text v-if="home.portfolio.plannedMinutes">本周已投入 {{ formatMinutes(home.portfolio.actualMinutes) }}</text></view>
					<button v-else class="hero-action" @tap="openCatalog">选择长期积累方向</button>
				</view>

				<view v-if="showCatalog || (!home.plans.length && !showPlanEditor)" class="catalog-panel">
					<view class="panel-heading catalog-heading">
						<view><text class="eyebrow">长期积累方向</text><text>你想先积累什么？</text></view>
						<button v-if="home.plans.length" @tap="showCatalog = false">×</button>
					</view>
					<text class="catalog-intro">先选择类型，再决定它在你的生活中具体是什么。一次最多进行 3 项。</text>
					<view class="catalog-tabs">
						<button :class="{ active: catalogMode === 'GROWTH' }" @tap="changeCatalogMode('GROWTH')">让成果继续增值 <text>{{ catalog.growth.length }}</text></button>
						<button :class="{ active: catalogMode === 'PROTECTION' }" @tap="changeCatalogMode('PROTECTION')">保护长期基础 <text>{{ catalog.protection.length }}</text></button>
					</view>
					<view v-if="catalogMode === 'PROTECTION'" class="protection-note">健康、关系和安全不一定无限增长，但会保护其他长期积累。</view>
					<view class="archetype-grid">
						<view v-for="(item, index) in visibleCatalogItems" :key="item.key" class="archetype-card" :class="{ selected: selectedArchetype && selectedArchetype.key === item.key }" @tap="selectArchetype(item)">
							<view class="archetype-number">{{ padNumber(index + 1) }}</view>
							<view class="archetype-copy"><text>{{ item.name }}</text><text v-if="selectedArchetype && selectedArchetype.key === item.key">{{ item.summary }}</text></view>
							<text class="archetype-arrow">›</text>
						</view>
					</view>
					<button v-if="catalogItems.length > 6" class="catalog-more" @tap="showAllArchetypes = !showAllArchetypes">{{ showAllArchetypes ? '收起其他方向' : '查看全部 ' + catalogItems.length + ' 个方向' }}</button>
					<view v-if="selectedArchetype" class="archetype-detail">
						<view class="detail-head"><view><text>{{ selectedArchetype.category }}</text><text>{{ selectedArchetype.name }}</text></view><text>{{ selectedArchetype.kind === 'PROTECTION' ? '保障原型' : '增长原型' }}</text></view>
						<view class="loop-statement"><text>它为什么会越做越有价值</text><text>{{ selectedArchetype.mechanism }}</text></view>
						<view class="fit-grid"><view><text>适合什么情况</text><text>{{ selectedArchetype.fits }}</text></view></view>
						<button class="detail-toggle dark" @tap="showArchetypeDetails = !showArchetypeDetails">{{ showArchetypeDetails ? '收起详细说明' : '我想进一步了解' }} <text>{{ showArchetypeDetails ? '−' : '+' }}</text></button>
						<view v-if="showArchetypeDetails" class="detail-more">
							<view class="fit-grid"><view><text>哪些情况不算</text><text>{{ selectedArchetype.notThis }}</text></view></view>
							<view class="default-measures"><view><text>持续积累什么</text><text>{{ selectedArchetype.defaultPrincipalMetric }}</text></view><view><text>观察什么结果</text><text>{{ selectedArchetype.defaultReturnMetric }}</text></view></view>
							<view class="example-list"><text>生活中的例子</text><text v-for="(example, exampleIndex) in selectedArchetype.examples" :key="exampleIndex">— {{ example }}</text></view>
							<view v-if="selectedArchetype.key === 'financial_capital'" class="finance-boundary dark"><text>使用边界</text><text>{{ selectedArchetype.setup.riskDisclosure }}</text></view>
						</view>
						<button class="primary-action" :disabled="home.portfolio.activeCount >= 3" @tap="startFromArchetype">用它建立我的计划</button>
					</view>
				</view>

				<view v-if="showPlanEditor" class="editor-panel plan-editor">
					<view class="panel-heading"><view><text class="eyebrow">{{ editingPlanId ? 'REVISE THE PLAN' : 'MAKE IT YOURS' }}</text><text>{{ editingPlanId ? '调整这项长期计划' : '让它成为我的计划' }}</text></view><button @tap="closeEditors">×</button></view>
					<view class="chosen-archetype"><text>{{ currentArchetypeKindLabel }}</text><view><text>{{ currentArchetypeName }}</text><text>{{ currentArchetypeSummary }}</text></view></view>
					<view v-if="isFinancialPlanDraft" class="finance-plan-fields">
						<view class="finance-boundary"><text>这里只帮你做计划和记清结果</text><text>不会推荐买什么，也不会承诺收益。下面一次只填写一步。</text></view>
						<view class="finance-step-progress"><view v-for="step in 4" :key="step" :class="{ active: financialPlanStep === step, done: financialPlanStep > step }"><text>{{ financialPlanStep > step ? '✓' : step }}</text><small>{{ financialStepLabel(step) }}</small></view></view>

						<template v-if="financialPlanStep === 1">
							<view class="finance-step-title"><text>1 / 4</text><strong>这笔长期资金为了什么？</strong><small>先确定目的和时间，不填写账户信息。</small></view>
							<label class="editor-field"><text>给计划起个名字</text><input v-model="planDraft.title" maxlength="240" placeholder="例如：十年长期投资" /></label>
							<label class="editor-field"><text>你希望它最终帮助你什么？</text><textarea v-model="planDraft.desiredOutcome" maxlength="1200" auto-height placeholder="例如：积累未来的选择权，不影响日常生活资金" /></label>
							<view class="finance-choice review"><text>准备坚持多少年</text><button v-for="years in [3,5,10,20]" :key="years" :class="{ active: Number(planDraft.financialTargetYears) === years }" @tap="planDraft.financialTargetYears = years">{{ years }} 年</button></view>
							<label class="editor-field compact"><text>其他年数</text><input v-model="planDraft.financialTargetYears" type="number" placeholder="1—60 年" /></label>
						</template>

						<template v-else-if="financialPlanStep === 2">
							<view class="finance-step-title"><text>2 / 4</text><strong>你准备怎样投入？</strong><small>这里填计划值，之后只按真实发生记录。</small></view>
							<view class="finance-choice"><button v-for="option in financialContributionOptions" :key="option.value" :class="{ active: planDraft.financialContributionMethod === option.value }" @tap="planDraft.financialContributionMethod = option.value">{{ option.label }}</button></view>
							<label v-if="planDraft.financialContributionMethod === 'FIXED'" class="editor-field compact"><text>每次计划投入多少（{{ planDraft.financialBaseCurrency }}）</text><input v-model="planDraft.financialFixedAmount" type="digit" placeholder="例如 3000" /></label>
							<label v-else-if="planDraft.financialContributionMethod === 'SURPLUS_RATIO'" class="editor-field compact"><text>每次投入可投资结余的百分比</text><input v-model="planDraft.financialSurplusRatio" type="digit" placeholder="例如 30" /></label>
							<label v-else-if="planDraft.financialContributionMethod === 'BATCHED_LUMP_SUM'" class="editor-field compact"><text>计划分批投入的总金额（{{ planDraft.financialBaseCurrency }}）</text><input v-model="planDraft.financialTotalBudget" type="digit" placeholder="例如 100000" /></label>
							<view class="finance-choice review"><text>多久投入一次</text><button v-for="option in financialFrequencyOptions" :key="option.value" :class="{ active: planDraft.financialFrequency === option.value }" @tap="planDraft.financialFrequency = option.value">{{ option.label }}</button></view>
						</template>

						<template v-else-if="financialPlanStep === 3">
							<view class="finance-step-title"><text>3 / 4</text><strong>你自己选择了哪些投资方向？</strong><small>Shroom 只记录，不推荐、不评级。</small></view>
							<label class="editor-field compact"><text>计划投资方向，一行一个</text><textarea v-model="planDraft.financialTargetLabelsText" maxlength="1000" auto-height placeholder="例如：\n全球股票指数基金\n现金管理" /></label>
							<view class="planned-not-held">写进计划，不代表已经买入。真实持有和金额以后单独记录。</view>
							<view class="finance-choice review"><text>从哪里开始记录</text><button :class="{ active: planDraft.financialTrackingMode === 'FROM_NOW' }" @tap="planDraft.financialTrackingMode = 'FROM_NOW'">从现在开始</button><button :class="{ active: planDraft.financialTrackingMode === 'HISTORY' }" @tap="planDraft.financialTrackingMode = 'HISTORY'">补录过去</button><button :class="{ active: planDraft.financialTrackingMode === 'PLAN_ONLY' }" @tap="planDraft.financialTrackingMode = 'PLAN_ONLY'">先只做计划</button></view>
						</template>

						<template v-else>
							<view class="finance-step-title"><text>4 / 4</text><strong>最后确认一次</strong><small>以后可以修改计划；所有金额仅当前账号可见。</small></view>
							<view class="finance-plan-summary"><text>你的计划</text><strong>{{ financialPlanSummary }}</strong><small>{{ planDraft.financialTargetLabelsText ? '投资方向：' + financialTargets.join(' · ') : '还没有填写投资方向' }}</small></view>
							<view class="finance-choice review"><text>这份计划覆盖</text><button :class="{ active: planDraft.financialScopeType === 'PARTIAL' }" @tap="planDraft.financialScopeType = 'PARTIAL'">一部分长期资金</button><button :class="{ active: planDraft.financialScopeType === 'ALL_LONG_TERM' }" @tap="planDraft.financialScopeType = 'ALL_LONG_TERM'">全部长期投资</button></view>
							<label class="editor-field compact"><text>记录金额使用的币种</text><input v-model="planDraft.financialBaseCurrency" maxlength="3" placeholder="CNY" /></label>
							<view class="finance-choice review"><text>多久检查一次是否按计划</text><button :class="{ active: planDraft.financialReviewFrequency === 'MONTHLY' }" @tap="planDraft.financialReviewFrequency = 'MONTHLY'">每月</button><button :class="{ active: planDraft.financialReviewFrequency === 'QUARTERLY' }" @tap="planDraft.financialReviewFrequency = 'QUARTERLY'">每季度</button></view>
							<checkbox-group v-if="!editingPlanId" class="boundary-consent" @change="changeFinancialBoundaryConsent"><label><checkbox value="accepted" :checked="planDraft.financialBoundaryAccepted" color="#172019" /><text>我知道 Shroom 不提供投资建议、收益保证或自动交易。</text></label></checkbox-group>
							<checkbox-group v-if="!editingPlanId" class="boundary-consent separate" @change="changeFinancialSensitiveConsent"><label><checkbox value="accepted" :checked="planDraft.financialSensitiveConsent" color="#172019" /><text>我同意仅在自己的账号中加密保存计划金额和投资方向。</text></label></checkbox-group>
							<button class="primary-action" :disabled="saving || !canSavePlan" @tap="savePlan">{{ saving ? '正在保存…' : '确认并创建计划' }}</button>
						</template>
						<view class="finance-step-nav"><button v-if="financialPlanStep > 1" @tap="financialPlanStep -= 1">上一步</button><button v-if="financialPlanStep < 4" class="next" :disabled="!canContinueFinancialStep" @tap="financialPlanStep += 1">下一步</button></view>
					</view>
					<template v-else>
						<view class="editor-intro"><text>只需要回答 4 件事</text><text>系统会根据你选的方向设置基础衡量，不需要你解释复利术语。</text></view>
						<label class="editor-field"><text>{{ planSetup.titleLabel }}</text><input v-model="planDraft.title" maxlength="240" :placeholder="planSetup.titlePlaceholder" /></label>
						<label class="editor-field"><text>{{ planSetup.commitmentLabel }}</text><textarea v-model="planDraft.principalDefinition" maxlength="1600" auto-height :placeholder="planSetup.commitmentPlaceholder" /></label>
						<label class="editor-field"><text>{{ planSetup.outcomeLabel }}</text><textarea v-model="planDraft.desiredOutcome" maxlength="1200" auto-height :placeholder="planSetup.outcomePlaceholder" /></label>
						<label class="editor-field"><text>{{ planSetup.nextStepLabel }}</text><textarea v-model="planDraft.currentStep" maxlength="1000" auto-height :placeholder="planSetup.nextStepPlaceholder" /></label>
						<view class="system-setup">
							<text>系统已经替你设定</text>
							<view><text>持续观察</text><text>{{ planDraft.principalMetricName || '真实投入' }}</text></view>
							<view><text>复利信号</text><text>{{ planDraft.returnMetricName || '旧积累产生真实回报' }}</text></view>
							<view><text>再投入规则</text><text>{{ planSetup.reinvestmentSummary }}</text></view>
						</view>
						<button class="advanced-toggle" @tap="showAdvancedPlan = !showAdvancedPlan">{{ showAdvancedPlan ? '收起可选设置' : '可选：调整衡量方式与不做清单' }} <text>{{ showAdvancedPlan ? '−' : '+' }}</text></button>
						<view v-if="showAdvancedPlan" class="advanced-panel">
							<view class="metric-editor"><view><text>持续投入按什么计数</text><input v-model="planDraft.principalMetricName" maxlength="240" placeholder="指标名称" /><input v-model="planDraft.principalMetricTarget" type="digit" placeholder="12 周次数" /></view><view><text>复利信号按什么计数</text><input v-model="planDraft.returnMetricName" maxlength="240" placeholder="指标名称" /><input v-model="planDraft.returnMetricTarget" type="digit" placeholder="12 周次数" /></view></view>
							<label class="editor-field"><text>每周愿意投入多少分钟</text><input v-model="planDraft.weeklyTimeBudgetMinutes" type="number" placeholder="120" /></label>
							<label class="editor-field"><text>为了保护它，这段时间明确不做（可选）</text><textarea v-model="planDraft.stopListText" maxlength="1800" auto-height placeholder="一行一项" /></label>
						</view>
						<view class="validation-notice"><text>先运行，再判断</text><text>创建后只是“验证中”。系统不会因为填完表单，就宣布复利已经成立。</text></view>
						<button class="primary-action" :disabled="saving || !canSavePlan" @tap="savePlan">{{ saving ? '正在保存…' : (editingPlanId ? '保存调整' : '开始这项长期计划') }}</button>
					</template>
				</view>

				<view v-if="showDeletePlanEditor && selectedPlan" class="editor-panel delete-plan-panel">
					<view class="panel-heading"><view><text class="eyebrow">DELETE COMPOUND PLAN</text><text>慎重删除这项复利计划</text></view><button @tap="closeEditors">×</button></view>
					<view class="delete-plan-name"><text>即将永久删除</text><strong>{{ selectedPlan.title }}</strong></view>
					<view class="delete-warning"><text>删除后无法恢复</text><text>这项计划、进度、复利证据、阶段配置，以及它专属的财务台账都会一起删除。</text><text>原始日记、人生 OS 和已有待办不会被删除；待办只会解除与本计划的关联。</text></view>
					<label class="editor-field"><text>请输入完整计划名称确认</text><input v-model="deletePlanConfirm" maxlength="240" :placeholder="selectedPlan.title" /></label>
					<button class="primary-action delete-confirm" :disabled="saving || deletePlanConfirm !== selectedPlan.title" @tap="deletePlan">{{ saving ? '正在删除…' : '永久删除这项计划' }}</button>
					<button class="cancel-delete" :disabled="saving" @tap="closeEditors">保留计划</button>
				</view>

				<template v-if="home.plans.length">
					<view class="section-intro"><view><text class="eyebrow">我的长期计划</text><text>现在正在积累</text></view><button @tap="openCatalog">添加计划</button></view>
					<view v-for="(plan, index) in home.plans" :key="plan.id" class="plan-card" :class="{ primary: index === 0, protection: plan.investmentKind === 'PROTECTION' }">
						<view class="plan-head"><view><text>{{ plan.archetype ? plan.archetype.name : '历史计划' }}</text><text>{{ plan.title }}</text></view><view class="plan-head-actions"><button class="more-action" :aria-label="'管理' + plan.title" @tap="openDeletePlan(plan)">•••</button></view></view>
						<view v-if="plan.archetypeKey === 'financial_capital'" class="validation-row"><text>计划进行中</text><text>每月检查一次</text></view>
						<view v-else class="validation-row"><text :class="{ validating: plan.validation.status === 'VALIDATING', compounding: plan.validation.status === 'COMPOUNDING', linear: plan.validation.status === 'LINEAR', protection: plan.validation.status === 'PROTECTION' }">{{ validationLabel(plan.validation.status, plan) }}</text><text>{{ plan.investmentKind === 'PROTECTION' ? '保障型' : '增长型' }}</text><text v-if="plan.validation.dueAt">首次判断 {{ compactDate(plan.validation.dueAt) }}</text><button @tap="openValidation(plan)">更新判断</button></view>
						<text class="plan-outcome">{{ plan.desiredOutcome }}</text>
						<template v-if="plan.archetypeKey === 'financial_capital'">
							<view class="plan-focus"><text>打开后能看到</text><text>投入多少 · 实际赚亏 · 持有什么 · 是否按计划</text></view>
							<button class="finance-open" @tap="openFinancialLedger(plan)">查看我的投资计划 <text>›</text></button>
						</template>
						<template v-else>
						<view class="next-step compact"><text>现在最重要的一步</text><text>{{ plan.currentStep }}</text><view><button @tap="createTask(plan, null)">加入待办</button><button @tap="openProgress(plan, null)">记录进展</button></view></view>
						<button class="plan-detail-toggle" @tap="togglePlanDetails(plan)">{{ expandedPlanId === plan.id ? '收起完整计划' : '查看完整计划和进度' }} <text>{{ expandedPlanId === plan.id ? '−' : '+' }}</text></button>
						<view v-if="expandedPlanId === plan.id" class="plan-details">
						<view class="compound-loop">
							<view><text>持续投入什么</text><text>{{ plan.principalDefinition || plan.compoundMechanism }}</text></view>
							<view><text>怎样产生回报</text><text>{{ plan.returnDefinition || '待补充' }}</text></view>
							<view><text>怎样进入下一轮</text><text>{{ plan.reinvestmentDefinition || '待补充' }}</text></view>
						</view>
						<view class="metric-pair">
							<view><text>投入进度</text><text>{{ plan.principalMetric.name || '待配置' }}</text><strong>{{ formatMetric(plan.principalMetric.current) }}<small> / {{ formatMetric(plan.principalMetric.target) }}</small></strong><view><view :style="{ width: plan.principalMetric.progressWidth }"></view></view></view>
							<view><text>回报信号</text><text>{{ plan.returnMetric.name || '待配置' }}</text><strong>{{ formatMetric(plan.returnMetric.current) }}<small> / {{ formatMetric(plan.returnMetric.target) }}</small></strong><view><view :style="{ width: plan.returnMetric.progressWidth }"></view></view></view>
						</view>
						<view class="plan-facts"><view><text>本周投入时间</text><text>{{ formatMinutes(plan.week.actualMinutes) }} / {{ formatMinutes(plan.week.plannedMinutes) }}</text></view><view><text>本轮计划</text><text>{{ compactDate(plan.cycleStart) }} — {{ compactDate(plan.cycleEnd) }}</text></view></view>
						<view class="milestone"><text>这一阶段要看到</text><text>{{ plan.currentMilestone || plan.desiredOutcome }}</text></view>
						<view class="week-plan">
							<view class="week-plan-head"><view><text>本周行动</text><text>{{ plan.week.actions.length ? completedActionCount(plan) + ' / ' + plan.week.actions.length + ' 项完成' : '还没有安排' }}</text></view><button @tap="openWeekEditor(plan)">{{ plan.week.actions.length ? '调整' : '安排' }}</button></view>
							<view v-for="action in plan.week.actions" :key="action.id" class="week-action" :class="{ done: action.completed }"><button class="action-check" :disabled="saving" @tap="toggleWeekAction(plan, action)">{{ action.completed ? '✓' : '' }}</button><button class="action-copy" @tap="openProgress(plan, action)"><text>{{ action.title }}</text><text>记录实际进展</text></button><button class="action-todo" @tap="createTask(plan, action)">待办</button></view>
							<view v-if="!plan.week.actions.length" class="week-empty"><text>先把本周真正愿意投入的时间和 1–3 个行动留下。</text><button @tap="openWeekEditor(plan)">配置时间与行动</button></view>
						</view>
						<view v-if="combinedStopList(plan).length" class="stop-list"><text>本周主动不做</text><text v-for="(item, stopIndex) in combinedStopList(plan)" :key="stopIndex">— {{ item }}</text></view>
						<button class="bottleneck-trigger" @tap="openBlocker(plan)">遇到阻碍，帮我找原因 →</button>
						</view>
						</template>
					</view>
				</template>

				<view v-if="showWeekEditor" class="editor-panel"><view class="panel-heading"><view><text class="eyebrow">WEEKLY ALLOCATION</text><text>{{ selectedPlan.title }} · 本周配置</text></view><button @tap="closeEditors">×</button></view><label class="editor-field"><text>本周真实分给它多少分钟</text><input v-model="weekDraft.plannedMinutes" type="number" /></label><label class="editor-field"><text>本周要完成的 1–5 个行动</text><textarea v-model="weekDraft.actionsText" maxlength="1800" auto-height placeholder="一行一项；行动要用来增加本金或验证回报。" /></label><label class="editor-field"><text>本周主动不做</text><textarea v-model="weekDraft.stopListText" maxlength="1200" auto-height placeholder="一行一项" /></label><button class="primary-action" :disabled="saving || !weekDraft.actionsText.trim()" @tap="saveWeekPlan">{{ saving ? '正在保存…' : '确认本周配置' }}</button></view>

				<view v-if="showProgressEditor" class="editor-panel"><view class="panel-heading"><view><text class="eyebrow">REAL EVIDENCE</text><text>{{ selectedPlan.title }} · 记录真实发生</text></view><button @tap="closeEditors">×</button></view><text v-if="progressDraft.weekActionTitle" class="linked-action">对应行动：{{ progressDraft.weekActionTitle }}</text><view v-if="selectedPlan.archetypeKey === 'financial_capital'" class="finance-boundary compact"><text>只写事实，不填账户信息</text><text>可以记录投入是否发生、费用和结果；不要填写账户、卡号、密码或验证码。</text></view><label class="editor-field"><text>发生了什么</text><textarea v-model="progressDraft.text" maxlength="5000" auto-height placeholder="写事实。AI 只会整理成可修改草稿。" /></label><view class="metric-editor"><view><text>投入时间（分钟）</text><input v-model="progressDraft.spentMinutes" type="number" placeholder="0" /></view><view><text>{{ selectedPlan.principalMetric.name || '本金指标' }} · 本次增加</text><input v-model="progressDraft.principalMetricDelta" type="digit" placeholder="0" /></view><view><text>{{ selectedPlan.returnMetric.name || '回报指标' }} · 本次增加</text><input v-model="progressDraft.returnMetricDelta" type="digit" placeholder="0" /></view></view><button class="primary-action" :disabled="saving || !progressDraft.text.trim()" @tap="prepareProgress">{{ saving ? '正在整理…' : '整理成可确认记录' }}</button></view>

				<view v-if="resultDraft" class="editor-panel result-editor"><view class="panel-heading"><view><text class="eyebrow">CONFIRM, DON'T ASSUME</text><text>确认证据后才计入</text></view><button @tap="resultDraft = null">×</button></view><label class="editor-field"><text>可观察的实际结果</text><textarea v-model="resultDraft.payload.actualResult" maxlength="1800" auto-height /></label><label class="editor-field"><text>下一步</text><textarea v-model="resultDraft.payload.nextStep" maxlength="1000" auto-height /></label><view class="confirm-ledger"><view><text>时间</text><text>{{ formatMinutes(progressDraft.spentMinutes) }}</text></view><view><text>{{ selectedPlan.principalMetric.name || '本金' }}</text><text>+{{ Number(progressDraft.principalMetricDelta) || 0 }}</text></view><view><text>{{ selectedPlan.returnMetric.name || '复用 / 回报' }}</text><text>+{{ Number(progressDraft.returnMetricDelta) || 0 }}</text></view></view><text class="confirmation-warning">数值必须是你能承担的真实记录；AI 不会自动证明复利。</text><button class="primary-action" :disabled="saving" @tap="confirmProgress">{{ saving ? '正在保存…' : '由我确认并计入' }}</button></view>

				<view v-if="showValidationEditor" class="editor-panel"><view class="panel-heading"><view><text class="eyebrow">VALIDATION JUDGEMENT</text><text>{{ selectedPlan.title }} · 现在是什么</text></view><button @tap="closeEditors">×</button></view><text class="validation-guidance">{{ validationGuidance }}</text><view class="validation-options"><button v-for="option in validationOptions" :key="option.value" :class="{ active: validationDraft.status === option.value }" @tap="validationDraft.status = option.value"><text>{{ option.label }}</text><text>{{ option.description }}</text></button></view><label class="editor-field"><text>支持这个判断的证据</text><textarea v-model="validationDraft.note" maxlength="1600" auto-height placeholder="只写真实发生的复用、回报、基线变化或线性投入事实。" /></label><button class="primary-action" :disabled="saving || (validationDraft.status !== 'VALIDATING' && !validationDraft.note.trim())" @tap="saveValidation">{{ saving ? '正在保存…' : '确认当前判断' }}</button></view>

				<view v-if="showBlockerEditor" class="editor-panel"><view class="panel-heading"><view><text class="eyebrow">BOTTLENECK</text><text>{{ selectedPlan.title }} · 最大瓶颈</text></view><button @tap="closeEditors">×</button></view><label class="editor-field"><text>具体卡在哪里</text><textarea v-model="blockerText" maxlength="1800" auto-height placeholder="是本金没有留下、无人复用、回报无法再投入，还是这项本身不值得？" /></label><button class="primary-action" :disabled="saving || !blockerText.trim()" @tap="submitBlocker">{{ saving ? '正在分析…' : '分析这一个瓶颈' }}</button><view v-if="blockerInsight" class="blocker-insight"><text>判断</text><text>{{ blockerInsight.payload.analysis || blockerInsight.summary }}</text><text v-if="blockerInsight.payload.adjustedStep">建议调整为</text><text v-if="blockerInsight.payload.adjustedStep">{{ blockerInsight.payload.adjustedStep }}</text><button v-if="blockerInsight.payload.adjustedStep" :disabled="saving" @tap="adoptBlocker">由我确认采用</button></view></view>

					<button v-if="home.diarySuggestions.length || home.recentResults.length" class="activity-toggle" @tap="showActivityHistory = !showActivityHistory"><view><text>日记反馈与近期进展</text><text>{{ home.diarySuggestions.length + home.recentResults.length }} 条记录，需要时再看</text></view><text>{{ showActivityHistory ? '−' : '+' }}</text></button>
					<view v-if="showActivityHistory && home.diarySuggestions.length" class="feedback-section"><view class="section-intro"><view><text class="eyebrow">来自日记</text><text>可能影响计划的现实反馈</text></view><text>{{ home.diarySuggestions.length }}</text></view><view v-for="item in home.diarySuggestions" :key="item.linkId" class="diary-feedback"><text>{{ item.sourceDate }} · {{ item.itemName }}</text><text>“{{ item.evidenceExcerpt }}”</text><view><button @tap="reviewDiary(item)">回看它怎样影响计划</button><button @tap="dismissDiary(item)">与计划无关</button></view></view></view>
				<view v-if="diaryReviewDraft" class="editor-panel"><view class="panel-heading"><view><text class="eyebrow">JOURNAL FEEDBACK</text><text>事实与推测分开看</text></view><button @tap="diaryReviewDraft = null">×</button></view><view class="review-list"><text>日记支持的事实</text><text v-for="(fact, factIndex) in diaryReviewDraft.payload.facts" :key="factIndex">— {{ fact }}</text></view><label class="editor-field"><text>下次尝试</text><textarea v-model="diaryReviewDraft.payload.nextTry" maxlength="1000" auto-height /></label><button class="primary-action" :disabled="saving" @tap="confirmDiaryReview">确认作为下一次尝试</button></view>

					<view v-if="showActivityHistory && home.recentResults.length" class="recent-section"><view class="section-intro"><view><text class="eyebrow">近期进展</text><text>已经确认的真实记录</text></view></view><view v-for="item in home.recentResults" :key="item.id" class="result-row"><view><text>{{ item.itemName }}</text><text>{{ eventTime(item.createdAt) }}</text></view><text>{{ item.payload.actualResult || item.summary }}</text><view class="result-meta"><text v-if="item.payload.spentMinutes">投入 {{ formatMinutes(item.payload.spentMinutes) }}</text><text v-if="item.payload.principalMetricDelta">持续投入 +{{ item.payload.principalMetricDelta }}</text><text v-if="item.payload.returnMetricDelta">回报 +{{ item.payload.returnMetricDelta }}</text></view></view></view>

				<view class="secondary-links"><button @tap="openReview"><view><text>阶段回看</text><text>用真实证据判断复利、线性积累或停止</text></view><text>›</text></button><button @tap="openYogaPractice"><view><text>身体练习</text><text>保障身体底盘的可选工具</text></view><text>›</text></button><button @tap="openPrinciples"><view><text>人生 OS</text><text>决定什么值得，但不自动创建复利项</text></view><text>›</text></button></view>
				<view class="privacy-note"><view></view><text>{{ home.privacy }}</text></view>
			</template>
		</view>
	</view>
</template>

<script>
import {
	compoundArchetypes, compoundBlocker, compoundDiaryDismiss, compoundDiaryReview,
	compoundDiaryReviewConfirm, compoundHome, compoundPlan, compoundPlanValidation,
	compoundPlanWeek, compoundPlanWeekAction, compoundResultConfirm, compoundResultDraft,
	compoundSuggestionAdopt, compoundThread, compoundThreadPrimary, compoundThreads, financialPlanProfile
} from '@/api/compound-system';

function pad(value) { return String(value).padStart(2, '0'); }
function localDate(value) { const date = value ? new Date(value + 'T12:00:00') : new Date(); return date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate()); }
function addDays(value, count) { const date = new Date(localDate(value) + 'T12:00:00'); date.setDate(date.getDate() + count); return localDate(date.getFullYear() + '-' + pad(date.getMonth() + 1) + '-' + pad(date.getDate())); }
function freshHome() { return { needsOnboarding: true, plans: [], diarySuggestions: [], recentResults: [], portfolio: { activeCount: 0, capacity: 3, weekStart: '', weekEnd: '', plannedMinutes: 0, actualMinutes: 0, utilizationPercent: 0, unplannedCount: 0 }, privacy: '复利计划、时间配置、进度与回看仅本人可见，不进入发现。' }; }
function percentWidth(value) { return Math.max(0, Math.min(100, Number(value) || 0)) + '%'; }
function decorateHome(value) {
	const home = { ...freshHome(), ...(value || {}) };
	home.portfolio = { ...freshHome().portfolio, ...(home.portfolio || {}) };
	home.portfolio.utilizationWidth = percentWidth(home.portfolio.utilizationPercent);
	home.plans = (home.plans || []).map(plan => ({
		...plan,
		principalMetric: { ...(plan.principalMetric || {}), progressWidth: percentWidth(plan.principalMetric && plan.principalMetric.progressPercent) },
		returnMetric: { ...(plan.returnMetric || {}), progressWidth: percentWidth(plan.returnMetric && plan.returnMetric.progressPercent) }
	}));
	return home;
}
function freshPlanDraft() { const start = localDate(); return { archetypeKey: '', title: '', desiredOutcome: '', principalDefinition: '', returnDefinition: '', reinvestmentDefinition: '', weeklyTimeBudgetMinutes: 120, principalMetricName: '', principalMetricTarget: 4, returnMetricName: '', returnMetricTarget: 1, outcomeEvidence: '', currentMilestone: '', currentStep: '', stopListText: '', cycleStart: start, cycleEnd: addDays(start, 83), financialBoundaryAccepted: false, financialSensitiveConsent: false, financialScopeType: 'PARTIAL', financialTrackingMode: 'FROM_NOW', financialBaseCurrency: 'CNY', financialTargetYears: 10, financialContributionMethod: 'FIXED', financialFixedAmount: '', financialFrequency: 'MONTHLY', financialSurplusRatio: '', financialTotalBudget: '', financialTargetLabelsText: '', financialReviewFrequency: 'MONTHLY' }; }
function fallbackPlanSetup(archetype) { return {
	titleLabel: '这项积累在你的生活里叫什么？', titlePlaceholder: '写一个具体、容易认出的名字',
	commitmentLabel: '你准备持续投入什么？', commitmentPlaceholder: '写一种能反复发生的投入',
	outcomeLabel: '12 周后看到什么，说明它值得继续？', outcomePlaceholder: '写一个你能亲自核对的变化或结果',
	nextStepLabel: '下一次最小的具体动作是什么？', nextStepPlaceholder: '写下离开页面后就能开始的一步',
	returnDefinition: archetype ? archetype.mechanism : '',
	reinvestmentDefinition: '已经确认的复用、节省或回报，会由你安排进入下一轮投入。',
	reinvestmentSummary: '系统会在进展回看时确认，真实回报是否进入了下一轮。',
	weeklyTimeBudgetMinutes: 120, principalMetricTarget: 4, returnMetricTarget: 1,
	currentMilestone: '四周内完成第一轮真实投入，并留下可以核对的结果'
}; }

export default {
	data() {
		return {
			statusBarHeight: 0, loading: true, loadError: false, saving: false,
			home: freshHome(), catalog: { growth: [], protection: [] }, catalogMode: 'GROWTH',
				showCatalog: false, showAllArchetypes: false, showArchetypeDetails: false, selectedArchetype: null, showPlanEditor: false, showAdvancedPlan: false,
				showWeekEditor: false, showProgressEditor: false, showValidationEditor: false,
				showBlockerEditor: false, showDeletePlanEditor: false, showActivityHistory: false, editingPlanId: '', expandedPlanId: '', selectedPlan: null,
				financialPlanStep: 1, planDraft: freshPlanDraft(), weekDraft: { plannedMinutes: 180, actionsText: '', stopListText: '' },
			progressDraft: { text: '', spentMinutes: '', principalMetricDelta: '', returnMetricDelta: '', weekActionId: '', weekActionTitle: '' },
			resultDraft: null, validationDraft: { status: 'VALIDATING', note: '' }, blockerText: '', blockerInsight: null, diaryReviewDraft: null, deletePlanConfirm: '',
			financialContributionOptions: [{ value: 'FIXED', label: '固定金额' }, { value: 'SURPLUS_RATIO', label: '按结余比例' }, { value: 'BATCHED_LUMP_SUM', label: '一次资金分批' }],
			financialFrequencyOptions: [{ value: 'MONTHLY', label: '每月' }, { value: 'QUARTERLY', label: '每季度' }, { value: 'YEARLY', label: '每年' }]
		};
	},
		computed: {
			catalogItems() { return this.catalogMode === 'PROTECTION' ? this.catalog.protection : this.catalog.growth; },
			visibleCatalogItems() { return this.showAllArchetypes ? this.catalogItems : this.catalogItems.slice(0, 6); },
		weekRange() { const p = this.home.portfolio || {}; return p.weekStart ? '本周 · ' + this.compactDate(p.weekStart) + ' — ' + this.compactDate(p.weekEnd) : 'COMPOUND OPPORTUNITY MAP'; },
		currentArchetype() { return this.selectedArchetype || (this.selectedPlan && this.selectedPlan.archetype) || null; },
		currentArchetypeName() { return this.currentArchetype ? this.currentArchetype.name : '历史计划'; },
		currentArchetypeSummary() { return this.currentArchetype ? this.currentArchetype.summary : '这项历史计划可以继续修订，新计划将从通用原型建立。'; },
		currentArchetypeKindLabel() { const item = this.currentArchetype; return item && item.kind === 'PROTECTION' ? '底盘保障' : '直接积累'; },
		planSetup() { const item = this.currentArchetype; return { ...fallbackPlanSetup(item), ...((item && item.setup) || {}) }; },
			isFinancialPlanDraft() { return Boolean(this.currentArchetype && this.currentArchetype.key === 'financial_capital'); },
			financialTargets() { return this.splitLines(this.planDraft.financialTargetLabelsText, 12); },
			financialContributionReady() { const d = this.planDraft; if (!d.financialFrequency) return false; if (d.financialContributionMethod === 'FIXED') return Number(d.financialFixedAmount) > 0; if (d.financialContributionMethod === 'SURPLUS_RATIO') return Number(d.financialSurplusRatio) > 0 && Number(d.financialSurplusRatio) <= 100; if (d.financialContributionMethod === 'BATCHED_LUMP_SUM') return Number(d.financialTotalBudget) > 0; return false; },
			financialRuleReady() { const years = Number(this.planDraft.financialTargetYears); return Number.isInteger(years) && years >= 1 && years <= 60 && this.financialTargets.length > 0 && this.financialContributionReady; },
			canContinueFinancialStep() { const d = this.planDraft; if (this.financialPlanStep === 1) { const years = Number(d.financialTargetYears); return Boolean(d.title.trim() && d.desiredOutcome.trim() && Number.isInteger(years) && years >= 1 && years <= 60); } if (this.financialPlanStep === 2) return this.financialContributionReady; if (this.financialPlanStep === 3) return Boolean(this.financialTargets.length && d.financialTrackingMode); return this.canSavePlan; },
		financialPlanSummary() { const d = this.planDraft; const years = Number(d.financialTargetYears); const cycle = { MONTHLY: '每月', QUARTERLY: '每季度', YEARLY: '每年' }[d.financialFrequency] || '每期'; if (!Number.isInteger(years) || years < 1) return ''; if (d.financialContributionMethod === 'FIXED' && Number(d.financialFixedAmount) > 0) { const periods = { MONTHLY: 12, QUARTERLY: 4, YEARLY: 1 }[d.financialFrequency] || 0; const total = Math.round(Number(d.financialFixedAmount) * periods * years); return years + ' 年 · ' + cycle + '投入 ' + d.financialBaseCurrency + ' ' + Number(d.financialFixedAmount).toLocaleString() + ' · 计划本金约 ' + d.financialBaseCurrency + ' ' + total.toLocaleString(); } if (d.financialContributionMethod === 'SURPLUS_RATIO' && Number(d.financialSurplusRatio) > 0) return years + ' 年 · ' + cycle + '投入可投资结余的 ' + Number(d.financialSurplusRatio) + '%'; if (d.financialContributionMethod === 'BATCHED_LUMP_SUM' && Number(d.financialTotalBudget) > 0) return years + ' 年 · ' + cycle + '分批 · 总额 ' + d.financialBaseCurrency + ' ' + Number(d.financialTotalBudget).toLocaleString(); return ''; },
		canSavePlan() { const d = this.planDraft; const boundaryReady = !this.isFinancialPlanDraft || Boolean(this.editingPlanId) || (d.financialBoundaryAccepted && d.financialSensitiveConsent); const principalReady = this.isFinancialPlanDraft || d.principalDefinition.trim(); const actionReady = this.isFinancialPlanDraft ? this.financialRuleReady : d.currentStep.trim(); return Boolean((this.editingPlanId || d.archetypeKey) && d.title.trim() && principalReady && d.desiredOutcome.trim() && actionReady && boundaryReady); },
		validationGuidance() {
			if (this.selectedPlan && this.selectedPlan.archetypeKey === 'financial_capital') return '这里只验证你的投入与再投入机制是否真实运行，不评价产品好坏，也不代表未来收益。没有经你确认的实际结果再投入记录时，不能标记为“再投入机制已验证”。';
			return '这是对真实证据的判断，不是自我评分。没有复用或回报证据时，系统不允许宣布“复利已成立”。';
		},
		validationOptions() {
			if (this.selectedPlan && this.selectedPlan.investmentKind === 'PROTECTION') return [
				{ value: 'VALIDATING', label: '继续验证', description: '还需要更多基线和变化证据' },
				{ value: 'PROTECTION', label: '保障有效', description: '已经观察到恢复力、稳定性或风险下降' }
			];
			if (this.selectedPlan && this.selectedPlan.archetypeKey === 'financial_capital') return [
				{ value: 'VALIDATING', label: '继续验证', description: '还需要更多真实投入与结果记录' },
				{ value: 'LINEAR', label: '目前只有投入', description: '投入已经发生，但还没有确认实际结果进入下一轮' },
				{ value: 'COMPOUNDING', label: '再投入机制已验证', description: '已有你确认的实际结果再投入记录；不代表未来收益' }
			];
			return [
				{ value: 'VALIDATING', label: '继续验证', description: '还不知道是否真的复利' },
				{ value: 'LINEAR', label: '目前线性', description: '有投入和积累，但旧积累还没有产生回报' },
				{ value: 'COMPOUNDING', label: '复利已出现', description: '已有可核对的复用或回报证据' }
			];
		}
	},
	onLoad() { this.statusBarHeight = uni.getSystemInfoSync().statusBarHeight || 0; },
	onShow() { this.loadAll(); },
	methods: {
			async loadAll() { this.loading = true; this.loadError = false; try { const results = await Promise.all([this.$http.get(compoundHome), this.$http.get(compoundArchetypes)]); this.home = decorateHome(results[0].data); this.catalog = { growth: results[1].data.growth || [], protection: results[1].data.protection || [] }; if (this.expandedPlanId && !this.home.plans.some(item => item.id === this.expandedPlanId)) this.expandedPlanId = ''; } catch (error) { this.loadError = true; console.error('加载复利系统失败', error); } finally { this.loading = false; } },
			openCatalog() { if (this.home.portfolio.activeCount >= 3) return uni.showToast({ title: '同时最多进行 3 项计划', icon: 'none' }); this.closeEditors(); this.showCatalog = true; this.showAllArchetypes = false; this.showArchetypeDetails = false; this.selectedArchetype = null; this.scrollTo(260); },
			openNewPlan() { this.openCatalog(); },
			changeCatalogMode(mode) { this.catalogMode = mode; this.selectedArchetype = null; this.showAllArchetypes = false; this.showArchetypeDetails = false; },
			openFinancialLedger(plan) { uni.navigateTo({ url: '/pages/shroom/financial-ledger?id=' + encodeURIComponent(plan.id) }); },
			togglePlanDetails(plan) { this.expandedPlanId = this.expandedPlanId === plan.id ? '' : plan.id; },
		openDeletePlan(plan) { this.closeEditors(); this.selectedPlan = plan; this.deletePlanConfirm = ''; this.showDeletePlanEditor = true; this.scrollTo(320); },
		async deletePlan() { if (!this.selectedPlan || this.saving || this.deletePlanConfirm !== this.selectedPlan.title) return; this.saving = true; try { await this.$http.delete(compoundThread(this.selectedPlan.id), { confirmText: '永久删除复利计划', confirmTitle: this.deletePlanConfirm }); this.closeEditors(); this.selectedPlan = null; await this.loadAll(); uni.showToast({ title: '复利计划已删除', icon: 'success' }); } catch (error) { uni.showToast({ title: error.message || '计划没有删除成功', icon: 'none' }); } finally { this.saving = false; } },
			selectArchetype(item) { this.selectedArchetype = item; this.showArchetypeDetails = false; setTimeout(() => this.scrollTo(560), 40); },
			startFromArchetype() { if (!this.selectedArchetype) return; const item = this.selectedArchetype; const setup = { ...fallbackPlanSetup(item), ...(item.setup || {}) }; this.editingPlanId = ''; this.selectedPlan = null; this.showAdvancedPlan = false; this.financialPlanStep = 1; this.planDraft = { ...freshPlanDraft(), archetypeKey: item.key, returnDefinition: setup.returnDefinition, reinvestmentDefinition: setup.reinvestmentDefinition, weeklyTimeBudgetMinutes: setup.weeklyTimeBudgetMinutes, principalMetricName: item.defaultPrincipalMetric, principalMetricTarget: setup.principalMetricTarget, returnMetricName: item.defaultReturnMetric, returnMetricTarget: setup.returnMetricTarget, currentMilestone: setup.currentMilestone }; this.showCatalog = false; this.showPlanEditor = true; this.scrollTo(260); },
		openEditPlan(plan) { this.closeEditors(); this.editingPlanId = plan.id; this.selectedPlan = plan; this.selectedArchetype = plan.archetype || null; this.showAdvancedPlan = false; this.planDraft = { archetypeKey: plan.archetypeKey || '', title: plan.title || '', desiredOutcome: plan.desiredOutcome || '', principalDefinition: plan.principalDefinition || plan.compoundMechanism || '', returnDefinition: plan.returnDefinition || plan.outcomeEvidence || '', reinvestmentDefinition: plan.reinvestmentDefinition || '由阶段回看确认如何再投入', weeklyTimeBudgetMinutes: plan.weeklyTimeBudgetMinutes || 120, principalMetricName: plan.principalMetric.name || plan.leadingMetric.name || '', principalMetricTarget: plan.principalMetric.target || plan.leadingMetric.target || 1, returnMetricName: plan.returnMetric.name || '', returnMetricTarget: plan.returnMetric.target || 1, outcomeEvidence: plan.outcomeEvidence || '', currentMilestone: plan.currentMilestone || '', currentStep: plan.currentStep || '', stopListText: (plan.stopList || []).join('\n'), cycleStart: plan.cycleStart, cycleEnd: plan.cycleEnd, financialBoundaryAccepted: true }; this.showPlanEditor = true; this.scrollTo(320); },
		planPayload() { const d = this.planDraft; const setup = this.planSetup; const item = this.currentArchetype; const financial = d.archetypeKey === 'financial_capital'; const principalDefinition = financial ? '用户定义的长期资金计划；计划标的与实际持有分开核对' : d.principalDefinition.trim(); const returnDefinition = d.returnDefinition.trim() || setup.returnDefinition || (item && item.mechanism) || ''; const reinvestmentDefinition = d.reinvestmentDefinition.trim() || setup.reinvestmentDefinition; const principalMetricName = d.principalMetricName.trim() || (item && item.defaultPrincipalMetric) || '真实投入'; const returnMetricName = d.returnMetricName.trim() || (item && item.defaultReturnMetric) || '真实回报'; const principalMetricTarget = financial ? 0 : (Number(d.principalMetricTarget) || Number(setup.principalMetricTarget) || 1); const returnMetricTarget = financial ? 0 : (Number(d.returnMetricTarget) || Number(setup.returnMetricTarget) || 1); const currentStep = financial ? this.financialFirstAction() : d.currentStep.trim(); return { archetypeKey: this.editingPlanId ? undefined : d.archetypeKey, title: d.title.trim(), desiredOutcome: d.desiredOutcome.trim(), principalDefinition, returnDefinition, reinvestmentDefinition, compoundMechanism: [principalDefinition, returnDefinition, reinvestmentDefinition].join('\n'), weeklyTimeBudgetMinutes: financial ? 0 : Math.round(Number(d.weeklyTimeBudgetMinutes) || Number(setup.weeklyTimeBudgetMinutes) || 120), principalMetricName, principalMetricTarget, returnMetricName, returnMetricTarget, leadingMetricName: principalMetricName, leadingMetricTarget: principalMetricTarget, outcomeEvidence: d.outcomeEvidence.trim() || d.desiredOutcome.trim(), currentMilestone: d.currentMilestone.trim() || setup.currentMilestone || d.desiredOutcome.trim(), currentStep, stopList: this.splitLines(d.stopListText, 8), cycleStart: d.cycleStart, cycleEnd: d.cycleEnd, contextReason: '用户从通用复利原型建立的私人验证项', financialBoundaryAccepted: d.financialBoundaryAccepted === true }; },
		financialFirstAction() { return { FROM_NOW: '记录基准日的计划总资产，并确认第一笔实际投入', HISTORY: '补录第一笔外部投入和对应历史市值', PLAN_ONLY: '发生第一次实际投入后确认记录' }[this.planDraft.financialTrackingMode] || '确认第一笔实际资金记录'; },
		financialSetupPayload() { const d = this.planDraft; return { purpose: d.desiredOutcome.trim(), scopeType: d.financialScopeType, trackingMode: d.financialTrackingMode, baseCurrency: d.financialBaseCurrency.trim().toUpperCase(), horizonStatus: 'TARGET_YEAR', targetYears: Number(d.financialTargetYears), reserveStatus: 'UNSPECIFIED', contributionMethod: d.financialContributionMethod, firstAction: this.financialFirstAction(), sensitiveDataConsent: d.financialSensitiveConsent === true, initialRule: { contributionMethod: d.financialContributionMethod, effectiveOn: localDate(), decidedOn: localDate(), currency: d.financialBaseCurrency.trim().toUpperCase(), fixedAmount: d.financialContributionMethod === 'FIXED' ? d.financialFixedAmount : '', frequency: d.financialFrequency, surplusRatio: d.financialContributionMethod === 'SURPLUS_RATIO' ? d.financialSurplusRatio : '', totalBudget: d.financialContributionMethod === 'BATCHED_LUMP_SUM' ? d.financialTotalBudget : '', targetLabels: this.financialTargets, reviewFrequency: d.financialReviewFrequency, returnDisposition: '', userLimits: '' } }; },
		async savePlan() { if (this.saving || !this.canSavePlan) return; this.saving = true; let financialId = ''; try { const payload = this.planPayload(); let response = null; if (this.editingPlanId) response = await this.$http.patch(compoundPlan(this.editingPlanId), payload); else response = await this.$http.post(compoundThreads, payload); financialId = this.isFinancialPlanDraft && response && response.data ? response.data.id : ''; if (financialId) await this.$http.put(financialPlanProfile(financialId), this.financialSetupPayload()); this.closeEditors(); await this.loadAll(); if (financialId) this.openFinancialLedger({ id: financialId }); else uni.showToast({ title: this.editingPlanId ? '计划已修订' : '已开始验证', icon: 'success' }); } catch (error) { if (financialId) { this.closeEditors(); await this.loadAll(); this.openFinancialLedger({ id: financialId }); uni.showToast({ title: '计划已创建，请补全资金设置', icon: 'none' }); } else uni.showToast({ title: error.message || '计划没有保存成功', icon: 'none' }); } finally { this.saving = false; } },
		openWeekEditor(plan) { this.closeEditors(); this.selectedPlan = plan; this.weekDraft = { plannedMinutes: plan.week.plannedMinutes || plan.weeklyTimeBudgetMinutes || 180, actionsText: (plan.week.actions || []).map(item => item.title).join('\n'), stopListText: (plan.week.stopList || []).join('\n') }; this.showWeekEditor = true; this.scrollTo(320); },
		async saveWeekPlan() { if (!this.selectedPlan || this.saving) return; const actions = this.splitLines(this.weekDraft.actionsText, 5); if (!actions.length || Number(this.weekDraft.plannedMinutes) <= 0) return; this.saving = true; try { await this.$http.put(compoundPlanWeek(this.selectedPlan.id), { plannedMinutes: Math.round(Number(this.weekDraft.plannedMinutes)), actions, stopList: this.splitLines(this.weekDraft.stopListText, 8) }); this.closeEditors(); await this.loadAll(); uni.showToast({ title: '本周配置已保存', icon: 'success' }); } catch (error) { uni.showToast({ title: error.message || '本周配置没有保存', icon: 'none' }); } finally { this.saving = false; } },
		async toggleWeekAction(plan, action) { if (this.saving) return; this.saving = true; try { await this.$http.patch(compoundPlanWeekAction(plan.id, action.id), { completed: !action.completed }); action.completed = !action.completed; } catch (error) { uni.showToast({ title: '行动状态没有保存', icon: 'none' }); } finally { this.saving = false; } },
		openProgress(plan, action) { this.closeEditors(); this.selectedPlan = plan; this.progressDraft = { text: action ? action.title + '：' : '', spentMinutes: action && action.plannedMinutes ? action.plannedMinutes : '', principalMetricDelta: '', returnMetricDelta: '', weekActionId: action ? action.id : '', weekActionTitle: action ? action.title : '' }; this.showProgressEditor = true; this.scrollTo(320); },
		async prepareProgress() { if (!this.selectedPlan || !this.progressDraft.text.trim() || this.saving) return; this.saving = true; try { const response = await this.$http.post(compoundResultDraft(this.selectedPlan.id), { text: this.progressDraft.text, mediaIds: [] }); this.resultDraft = response.data.event; this.showProgressEditor = false; } catch (error) { uni.showToast({ title: '这次证据没有整理好', icon: 'none' }); } finally { this.saving = false; } },
		async confirmProgress() { if (!this.selectedPlan || !this.resultDraft || this.saving) return; this.saving = true; try { await this.$http.post(compoundResultConfirm(this.selectedPlan.id, this.resultDraft.id), { ...this.resultDraft.payload, closeMode: 'CONTINUE', spentMinutes: Math.round(Number(this.progressDraft.spentMinutes) || 0), principalMetricDelta: Number(this.progressDraft.principalMetricDelta) || 0, returnMetricDelta: Number(this.progressDraft.returnMetricDelta) || 0, leadingMetricDelta: Number(this.progressDraft.principalMetricDelta) || 0, weekActionId: this.progressDraft.weekActionId }); this.resultDraft = null; this.selectedPlan = null; await this.loadAll(); uni.showToast({ title: '真实证据已计入', icon: 'success' }); } catch (error) { uni.showToast({ title: error.message || '证据没有保存', icon: 'none' }); } finally { this.saving = false; } },
		openValidation(plan) { this.closeEditors(); this.selectedPlan = plan; this.validationDraft = { status: plan.validation.status || 'VALIDATING', note: plan.validation.note || '' }; this.showValidationEditor = true; this.scrollTo(320); },
		async saveValidation() { if (!this.selectedPlan || this.saving) return; this.saving = true; try { await this.$http.patch(compoundPlanValidation(this.selectedPlan.id), this.validationDraft); this.closeEditors(); await this.loadAll(); uni.showToast({ title: '当前判断已更新', icon: 'success' }); } catch (error) { uni.showToast({ title: error.message || '现在还不能确认这个判断', icon: 'none' }); } finally { this.saving = false; } },
		openBlocker(plan) { this.closeEditors(); this.selectedPlan = plan; this.blockerText = plan.blockerSummary || ''; this.blockerInsight = null; this.showBlockerEditor = true; this.scrollTo(320); },
		async submitBlocker() { if (!this.selectedPlan || !this.blockerText.trim() || this.saving) return; this.saving = true; try { await this.$http.post(compoundThreadPrimary(this.selectedPlan.id), {}); const response = await this.$http.post(compoundBlocker(this.selectedPlan.id), { blocker: this.blockerText }); this.blockerInsight = response.data.event; } catch (error) { uni.showToast({ title: '瓶颈暂时没有分析完成', icon: 'none' }); } finally { this.saving = false; } },
		async adoptBlocker() { if (!this.selectedPlan || !this.blockerInsight || this.saving) return; this.saving = true; try { await this.$http.post(compoundSuggestionAdopt(this.selectedPlan.id, this.blockerInsight.id), { currentStep: this.blockerInsight.payload.adjustedStep }); this.closeEditors(); await this.loadAll(); } finally { this.saving = false; } },
		async reviewDiary(item) { if (!this.home.current || this.saving) return; this.saving = true; try { const response = await this.$http.post(compoundDiaryReview(this.home.current.id, item.linkId), {}); this.diaryReviewDraft = response.data.event; } catch (error) { uni.showToast({ title: '这次日记暂时没有回看完成', icon: 'none' }); } finally { this.saving = false; } },
		async confirmDiaryReview() { if (!this.home.current || !this.diaryReviewDraft || this.saving) return; this.saving = true; try { await this.$http.post(compoundDiaryReviewConfirm(this.home.current.id, this.diaryReviewDraft.id), this.diaryReviewDraft.payload); this.diaryReviewDraft = null; await this.loadAll(); } finally { this.saving = false; } },
		async dismissDiary(item) { if (!this.home.current || this.saving) return; this.saving = true; try { await this.$http.post(compoundDiaryDismiss(this.home.current.id, item.linkId), {}); await this.loadAll(); } finally { this.saving = false; } },
			changeFinancialBoundaryConsent(event) { this.planDraft.financialBoundaryAccepted = Boolean(event.detail && event.detail.value && event.detail.value.includes('accepted')); },
			changeFinancialSensitiveConsent(event) { this.planDraft.financialSensitiveConsent = Boolean(event.detail && event.detail.value && event.detail.value.includes('accepted')); },
			financialStepLabel(step) { return ['目的', '投入', '方向', '确认'][step - 1] || ''; },
		createTask(plan, action) { const title = action ? action.title : plan.currentStep; uni.setStorageSync('todoPrefill', { title, description: '服务于复利验证项：' + plan.title + '\n\n12 周结果：' + plan.desiredOutcome, compoundItemId: plan.itemId || undefined, sourceType: 'COMPOUND', sourceRefId: plan.id, sourceCompoundThreadId: plan.id }); uni.navigateTo({ url: '/pages/todo/list' }); },
			closeEditors() { this.showPlanEditor = false; this.showAdvancedPlan = false; this.showWeekEditor = false; this.showProgressEditor = false; this.showValidationEditor = false; this.showBlockerEditor = false; this.showDeletePlanEditor = false; this.financialPlanStep = 1; this.resultDraft = null; this.blockerInsight = null; this.diaryReviewDraft = null; this.deletePlanConfirm = ''; },
		scrollTo(value) { setTimeout(() => uni.pageScrollTo({ scrollTop: value, duration: 240 }), 40); },
		splitLines(value, max) { return String(value || '').split(/\r?\n/).map(item => item.trim()).filter(Boolean).slice(0, max); },
		combinedStopList(plan) { const source = plan.week.stopList && plan.week.stopList.length ? plan.week.stopList : plan.stopList; return (source || []).slice(0, 5); },
		completedActionCount(plan) { return (plan.week.actions || []).filter(item => item.completed).length; },
		validationLabel(value, plan) { if (plan && plan.archetypeKey === 'financial_capital') return { VALIDATING: '验证中', COMPOUNDING: '再投入机制已验证', LINEAR: '目前只有投入' }[value] || '验证中'; return { VALIDATING: '验证中', COMPOUNDING: '复利已出现', LINEAR: '目前线性', PROTECTION: '保障有效' }[value] || '验证中'; },
		formatMetric(value) { const number = Number(value) || 0; return Number.isInteger(number) ? String(number) : number.toFixed(1); },
		formatMinutes(value) { const minutes = Math.max(0, Math.round(Number(value) || 0)); if (minutes < 60) return minutes + ' 分钟'; const hours = Math.floor(minutes / 60); const remainder = minutes % 60; return remainder ? hours + ' 小时 ' + remainder + ' 分' : hours + ' 小时'; },
		compactDate(value) { return String(value || '').slice(5).replace('-', '.'); },
		eventTime(value) { return String(value || '').replace('T', ' ').slice(0, 16); },
		padNumber(value) { return String(value).padStart(2, '0'); },
		openReview() { uni.navigateTo({ url: '/pages/shroom/life-os-weekly' }); },
		openYogaPractice() { uni.navigateTo({ url: '/pages/shroom/yoga-practice' }); },
		openPrinciples() { uni.navigateTo({ url: '/pages/shroom/life-os' }); },
		goBack() { const pages = getCurrentPages(); if (pages.length > 1) uni.navigateBack(); else uni.switchTab({ url: '/pages/diary/index' }); }
	}
};
</script>

<style lang="scss" scoped>
button { margin: 0; padding: 0; line-height: 1.25; background: transparent; border: 0; }
button::after { border: 0; }
button[disabled] { opacity: .42; }
input, textarea { box-sizing: border-box; width: 100%; color: #172019; font-size: 21rpx; line-height: 1.55; }
.compound-page { min-height: 100vh; background: #f0f6e9; color: #172019; }
.status-bar { background: #f0f6e9; }
.page-shell { box-sizing: border-box; padding: 26rpx 30rpx 140rpx; }
.topbar { display: flex; align-items: center; gap: 17rpx; }
.round-button { display: flex; width: 68rpx; height: 68rpx; flex: 0 0 68rpx; align-items: center; justify-content: center; border: 1rpx solid rgba(23,32,25,.1); border-radius: 50%; background: rgba(255,255,255,.72); font-size: 46rpx; }
.add-button { background: #172019; color: #fff; font-size: 35rpx; }
.topbar-copy { display: flex; min-width: 0; flex: 1; flex-direction: column; }
.topbar-kicker, .eyebrow { color: #718075; font-size: 14rpx; font-weight: 760; letter-spacing: 2.4rpx; }
.topbar-title { margin-top: 5rpx; font-family: Georgia, 'Songti SC', serif; font-size: 37rpx; font-weight: 720; }
.state-card { display: flex; min-height: 270rpx; margin-top: 26rpx; align-items: center; justify-content: center; gap: 16rpx; border-radius: 35rpx; background: #fff; color: #748078; font-size: 20rpx; }
.state-card.error { flex-direction: column; }.loading-dot { width: 13rpx; height: 13rpx; border-radius: 50%; background: #5b725f; animation: pulse 1s infinite alternate; }.dark-pill { padding: 18rpx 30rpx; border-radius: 999rpx; background: #172019; color: #fff; }
@keyframes pulse { to { opacity: .25; transform: scale(.7); } }
.portfolio-hero { margin-top: 27rpx; padding: 42rpx 37rpx 34rpx; overflow: hidden; border-radius: 39rpx; background: #172019; color: #fff; }
.portfolio-hero.empty { background: linear-gradient(145deg,#152019 0%,#26392b 65%,#657b4d 130%); }
.portfolio-hero .eyebrow { color: #a7b5a8; }.portfolio-title { display: block; max-width: 620rpx; margin-top: 18rpx; font-family: Georgia, 'Songti SC', serif; font-size: 47rpx; font-weight: 720; line-height: 1.22; }.portfolio-copy { display: block; max-width: 610rpx; margin-top: 17rpx; color: #b9c4ba; font-size: 20rpx; line-height: 1.7; }
.hero-action { margin-top: 31rpx; padding: 21rpx 29rpx; border-radius: 999rpx; background: #e5efd9; color: #172019; font-size: 19rpx; font-weight: 720; }
.week-ledger { display: flex; margin-top: 31rpx; padding-top: 25rpx; border-top: 1rpx solid rgba(255,255,255,.13); }.week-ledger view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 8rpx; }.week-ledger view + view { padding-left: 20rpx; border-left: 1rpx solid rgba(255,255,255,.12); }.week-ledger text:first-child { color: #9eaa9f; font-size: 15rpx; }.week-ledger text:last-child { font-size: 23rpx; font-weight: 690; }
.portfolio-progress { display: flex; align-items: center; gap: 15rpx; margin-top: 21rpx; }.portfolio-progress > view { height: 7rpx; overflow: hidden; flex: 1; border-radius: 99rpx; background: rgba(255,255,255,.13); }.portfolio-progress > view > view { height: 100%; border-radius: inherit; background: #dcebcc; }.portfolio-progress > text { color: #b7c2b8; font-size: 15rpx; }
.catalog-panel, .editor-panel, .plan-card, .feedback-section, .recent-section { margin-top: 24rpx; padding: 31rpx; border-radius: 34rpx; background: #fff; }
.catalog-panel { padding: 34rpx 29rpx; }.panel-heading, .section-intro { display: flex; align-items: flex-end; justify-content: space-between; gap: 20rpx; }.panel-heading > view, .section-intro > view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 7rpx; }.panel-heading > view > text:last-child, .section-intro > view > text:last-child { font-family: Georgia, 'Songti SC', serif; font-size: 29rpx; font-weight: 690; }.panel-heading > button { color: #6f7b72; font-size: 33rpx; }.section-intro { margin-top: 34rpx; padding: 0 4rpx; }.section-intro > button { color: #4e6753; font-size: 17rpx; }.section-intro > text { color: #6d7a70; font-size: 18rpx; }
.catalog-intro { display: block; margin-top: 17rpx; color: #69766d; font-size: 18rpx; line-height: 1.65; }.catalog-tabs { display: flex; margin-top: 25rpx; padding: 6rpx; border-radius: 18rpx; background: #edf1ea; }.catalog-tabs button { display: flex; min-height: 61rpx; flex: 1; align-items: center; justify-content: center; gap: 8rpx; border-radius: 14rpx; color: #69756c; font-size: 17rpx; }.catalog-tabs button.active { background: #172019; color: #fff; box-shadow: 0 4rpx 12rpx rgba(23,32,25,.13); }.catalog-tabs text { opacity: .68; font-size: 14rpx; }.protection-note { margin-top: 19rpx; padding: 18rpx 20rpx; border-radius: 18rpx; background: #f4eedf; color: #71664e; font-size: 17rpx; line-height: 1.55; }
.archetype-grid { margin-top: 19rpx; }.archetype-card { display: flex; align-items: flex-start; gap: 16rpx; padding: 22rpx 7rpx; border-top: 1rpx solid #e8ede6; }.archetype-card:first-child { border-top: 0; }.archetype-card.selected { margin: 0 -10rpx; padding-right: 17rpx; padding-left: 17rpx; border-radius: 20rpx; background: #eff4e9; }.archetype-number { padding-top: 3rpx; color: #7e8d82; font-size: 15rpx; font-weight: 760; }.archetype-copy { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 8rpx; }.archetype-copy text:first-child { font-size: 22rpx; font-weight: 700; }.archetype-copy text:last-child { color: #69756c; font-size: 17rpx; line-height: 1.55; }.archetype-arrow { color: #7a887e; font-size: 27rpx; }
.archetype-detail { margin-top: 21rpx; padding: 27rpx; border-radius: 27rpx; background: #172019; color: #fff; }.detail-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 20rpx; }.detail-head > view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 5rpx; }.detail-head > view text:first-child { color: #99a89b; font-size: 14rpx; letter-spacing: 1rpx; }.detail-head > view text:last-child { font-family: Georgia, 'Songti SC', serif; font-size: 28rpx; }.detail-head > text { padding: 8rpx 12rpx; border: 1rpx solid rgba(255,255,255,.18); border-radius: 999rpx; color: #c3cdc4; font-size: 13rpx; }.loop-statement { display: flex; margin-top: 25rpx; padding: 21rpx 0; flex-direction: column; gap: 8rpx; border-top: 1rpx solid rgba(255,255,255,.12); border-bottom: 1rpx solid rgba(255,255,255,.12); }.loop-statement text:first-child, .fit-grid view text:first-child, .example-list > text:first-child { color: #9daaa0; font-size: 14rpx; font-weight: 710; letter-spacing: 1rpx; }.loop-statement text:last-child { font-size: 19rpx; line-height: 1.62; }.fit-grid { display: flex; gap: 22rpx; margin-top: 23rpx; }.fit-grid view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 8rpx; }.fit-grid view text:last-child { color: #c4cdc5; font-size: 16rpx; line-height: 1.55; }.default-measures { display: flex; gap: 13rpx; margin-top: 22rpx; }.default-measures view { display: flex; min-width: 0; padding: 17rpx; flex: 1; flex-direction: column; gap: 7rpx; border-radius: 17rpx; background: rgba(255,255,255,.08); }.default-measures text:first-child { color: #9daa9e; font-size: 13rpx; }.default-measures text:last-child { font-size: 16rpx; line-height: 1.45; }.example-list { display: flex; margin-top: 22rpx; flex-direction: column; gap: 8rpx; }.example-list text:not(:first-child) { color: #c6cfc7; font-size: 16rpx; line-height: 1.5; }.archetype-detail .primary-action { background: #e4efd8; color: #172019; }
.chosen-archetype { display: flex; align-items: flex-start; gap: 16rpx; margin-top: 23rpx; padding: 20rpx; border-radius: 21rpx; background: #edf3e8; }.chosen-archetype > text { flex: 0 0 auto; padding: 7rpx 11rpx; border-radius: 999rpx; background: #dbe7d3; color: #526156; font-size: 13rpx; }.chosen-archetype > view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 6rpx; }.chosen-archetype > view text:first-child { font-size: 20rpx; font-weight: 700; }.chosen-archetype > view text:last-child { color: #69756c; font-size: 15rpx; line-height: 1.5; }
.finance-boundary { display: flex; margin-top: 20rpx; padding: 20rpx; flex-direction: column; gap: 7rpx; border: 1rpx solid #dfd4b7; border-radius: 19rpx; background: #f7f1df; color: #665c45; }.finance-boundary text:first-child { font-size: 17rpx; font-weight: 720; }.finance-boundary text:last-child { font-size: 15rpx; line-height: 1.6; }.finance-boundary.dark { border-color: rgba(229,239,217,.2); background: rgba(229,239,217,.09); color: #d8e0d8; }.finance-boundary.dark text:first-child { color: #eef3ed; }.finance-boundary.compact { padding: 17rpx 19rpx; }.boundary-consent { margin-top: 21rpx; }.boundary-consent label { display: flex; align-items: flex-start; gap: 12rpx; color: #5e665e; font-size: 16rpx; line-height: 1.55; }.boundary-consent checkbox { flex: 0 0 auto; transform: scale(.82); transform-origin: top left; }
.finance-entry-grid { display: grid; margin-top: 20rpx; grid-template-columns: 1fr 1fr; gap: 10rpx; }.finance-entry-grid view { display: flex; padding: 17rpx; flex-direction: column; gap: 5rpx; border-radius: 17rpx; background: #f1f5ee; }.finance-entry-grid text:first-child { color: #849087; font-size: 12rpx; font-weight: 760; }.finance-entry-grid text:last-child { color: #465448; font-size: 16rpx; font-weight: 680; }.finance-open { display: flex; width: 100%; min-height: 72rpx; margin-top: 18rpx; align-items: center; justify-content: space-between; padding: 0 23rpx; border-radius: 22rpx; background: #172019; color: #fff; font-size: 18rpx; font-weight: 720; }.finance-open text { font-size: 30rpx; font-weight: 400; }
.editor-intro { display: flex; margin-top: 21rpx; padding: 19rpx 20rpx; flex-direction: column; gap: 5rpx; border-left: 5rpx solid #5f765f; border-radius: 0 17rpx 17rpx 0; background: #f3f6f0; }.editor-intro text:first-child { font-size: 18rpx; font-weight: 720; }.editor-intro text:last-child { color: #718075; font-size: 15rpx; line-height: 1.55; }
.finance-plan-fields { display: flex; margin-top: 23rpx; flex-direction: column; }.finance-step { display: flex; margin-top: 26rpx; align-items: flex-start; gap: 13rpx; }.finance-step:first-child { margin-top: 0; }.finance-step > text { display: flex; width: 36rpx; height: 36rpx; flex: 0 0 36rpx; align-items: center; justify-content: center; border-radius: 50%; background: #172019; color: #fff; font-size: 13rpx; font-weight: 760; }.finance-step > view { display: flex; min-width: 0; flex-direction: column; gap: 4rpx; }.finance-step strong { font-size: 19rpx; }.finance-step small { color: #788178; font-size: 13rpx; line-height: 1.45; }.finance-choice { display: flex; margin-top: 13rpx; gap: 8rpx; flex-wrap: wrap; }.finance-choice > text { width: 100%; color: #657067; font-size: 14rpx; font-weight: 700; }.finance-choice button { min-height: 53rpx; padding: 12rpx 16rpx; border: 1rpx solid #dce4d9; border-radius: 999rpx; background: #f8faf6; color: #657067; font-size: 14rpx; }.finance-choice button.active { border-color: #4d6753; background: #e5eee0; color: #2f4735; font-weight: 720; }.editor-field.compact { margin-top: 13rpx; }.planned-not-held { margin-top: 9rpx; padding: 14rpx 16rpx; border-radius: 14rpx; background: #f7f1df; color: #746548; font-size: 13rpx; line-height: 1.5; }.finance-plan-summary { display: flex; margin-top: 22rpx; padding: 20rpx; flex-direction: column; gap: 6rpx; border-radius: 18rpx; background: #172019; color: #fff; }.finance-plan-summary > text { color: #aeb8af; font-size: 13rpx; }.finance-plan-summary strong { font-size: 17rpx; line-height: 1.55; }.finance-plan-summary small { color: #aeb8af; font-size: 12rpx; line-height: 1.45; }.boundary-consent.separate { padding-top: 17rpx; border-top: 1rpx solid #e3e8e1; }
.editor-field { display: flex; margin-top: 22rpx; flex-direction: column; gap: 9rpx; }.editor-field > text { color: #5f6d63; font-size: 17rpx; font-weight: 650; }.editor-field input, .editor-field textarea, .metric-editor input { min-height: 69rpx; padding: 18rpx 20rpx; border: 1rpx solid #dfe6dc; border-radius: 18rpx; background: #f8faf6; }.editor-field textarea { min-height: 94rpx; }
.system-setup { display: flex; margin-top: 24rpx; padding: 21rpx; flex-direction: column; gap: 13rpx; border-radius: 20rpx; background: #172019; color: #fff; }.system-setup > text { color: #a7b3a8; font-size: 14rpx; font-weight: 720; letter-spacing: 1rpx; }.system-setup > view { display: grid; grid-template-columns: 120rpx 1fr; gap: 12rpx; }.system-setup > view text:first-child { color: #8f9d91; font-size: 14rpx; }.system-setup > view text:last-child { color: #e7ece7; font-size: 16rpx; line-height: 1.5; }
.advanced-toggle { display: flex; width: 100%; margin-top: 17rpx; align-items: center; justify-content: space-between; padding: 15rpx 3rpx; color: #69766d; font-size: 15rpx; text-align: left; }.advanced-toggle text { font-size: 22rpx; }.advanced-panel { margin-top: 4rpx; padding: 4rpx 19rpx 20rpx; border: 1rpx solid #e2e8df; border-radius: 21rpx; background: #fbfcfa; }
.two-column, .metric-editor { display: flex; gap: 14rpx; }.two-column > * { flex: 1; }.metric-editor { margin-top: 22rpx; }.metric-editor > view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 9rpx; }.metric-editor > view > text { color: #5f6d63; font-size: 16rpx; font-weight: 650; }.metric-editor input { min-height: 63rpx; font-size: 17rpx; }.validation-notice { display: flex; margin-top: 24rpx; padding: 20rpx; flex-direction: column; gap: 7rpx; border-radius: 19rpx; background: #f2eedf; }.validation-notice text:first-child { color: #5d5544; font-size: 18rpx; font-weight: 700; }.validation-notice text:last-child { color: #746b58; font-size: 16rpx; line-height: 1.55; }.primary-action { width: 100%; min-height: 74rpx; margin-top: 26rpx; padding: 18rpx 24rpx; border-radius: 999rpx; background: #172019; color: #fff; font-size: 19rpx; font-weight: 720; }
.plan-card.primary { box-shadow: inset 0 5rpx 0 #55725b; }.plan-card.protection { box-shadow: inset 0 5rpx 0 #af955f; }.plan-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 18rpx; }.plan-head > view:first-child { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 8rpx; }.plan-head > view:first-child text:first-child { color: #738078; font-size: 14rpx; letter-spacing: 1rpx; }.plan-head > view:first-child text:last-child { font-family: Georgia, 'Songti SC', serif; font-size: 31rpx; font-weight: 700; line-height: 1.25; }.plan-head-actions { display: flex; flex: 0 0 auto; align-items: center; gap: 13rpx; }.plan-head-actions button { padding: 8rpx 0 10rpx 14rpx; color: #66746a; font-size: 16rpx; }.plan-head-actions .more-action { min-width: 48rpx; padding-left: 5rpx; color: #89928b; letter-spacing: 2rpx; }.validation-row { display: flex; align-items: center; gap: 9rpx; margin-top: 17rpx; flex-wrap: wrap; }.validation-row > text { padding: 7rpx 11rpx; border-radius: 999rpx; background: #eef2eb; color: #6b776e; font-size: 13rpx; }.validation-row > text:first-child { color: #4f604f; background: #dfe9d8; font-weight: 700; }.validation-row > text.compounding { background: #d8ead7; color: #2d6236; }.validation-row > text.linear { background: #eee7d8; color: #705e39; }.validation-row > text.protection { background: #ece3cc; color: #6a5730; }.validation-row > button { margin-left: auto; color: #4e6753; font-size: 14rpx; }.plan-outcome { display: block; margin-top: 19rpx; color: #4f5e53; font-size: 20rpx; line-height: 1.62; }
.delete-plan-name { display: flex; margin-top: 22rpx; padding: 20rpx; flex-direction: column; gap: 7rpx; border-radius: 19rpx; background: #f0f3ed; }.delete-plan-name text { color: #778078; font-size: 14rpx; }.delete-plan-name strong { overflow-wrap: anywhere; font-family: Georgia, 'Songti SC', serif; font-size: 25rpx; }.delete-warning { display: flex; margin-top: 17rpx; padding: 21rpx; flex-direction: column; gap: 8rpx; border: 1rpx solid #ead2cc; border-radius: 20rpx; background: #f8e9e4; color: #765047; }.delete-warning text:first-child { font-size: 18rpx; font-weight: 750; }.delete-warning text:not(:first-child) { font-size: 15rpx; line-height: 1.58; }.primary-action.delete-confirm { background: #7c433b; }.cancel-delete { width: 100%; margin-top: 15rpx; padding: 17rpx; color: #687269; font-size: 16rpx; }
.compound-loop { margin-top: 23rpx; border-top: 1rpx solid #e5eae3; }.compound-loop > view { display: grid; padding: 18rpx 0; border-bottom: 1rpx solid #edf0eb; grid-template-columns: 150rpx 1fr; gap: 14rpx; }.compound-loop text:first-child { color: #79867d; font-size: 14rpx; font-weight: 700; letter-spacing: .6rpx; }.compound-loop text:last-child { color: #48564c; font-size: 17rpx; line-height: 1.55; }
.metric-pair { display: flex; gap: 12rpx; margin-top: 21rpx; }.metric-pair > view { display: flex; min-width: 0; padding: 19rpx; flex: 1; flex-direction: column; border-radius: 20rpx; background: #f0f4ed; }.metric-pair > view > text:first-child { color: #718075; font-size: 14rpx; font-weight: 710; }.metric-pair > view > text:nth-child(2) { min-height: 46rpx; margin-top: 6rpx; color: #59665c; font-size: 15rpx; line-height: 1.45; }.metric-pair strong { margin-top: 9rpx; font-size: 25rpx; }.metric-pair small { color: #849087; font-size: 14rpx; font-weight: 500; }.metric-pair > view > view { height: 6rpx; margin-top: 13rpx; overflow: hidden; border-radius: 99rpx; background: #dce4d9; }.metric-pair > view > view > view { height: 100%; border-radius: inherit; background: #5a755f; }
.plan-facts { display: flex; margin-top: 18rpx; padding: 17rpx 0; border-top: 1rpx solid #e8ece6; border-bottom: 1rpx solid #e8ece6; }.plan-facts view { display: flex; flex: 1; flex-direction: column; gap: 5rpx; }.plan-facts view + view { padding-left: 21rpx; border-left: 1rpx solid #e5e9e3; }.plan-facts text:first-child { color: #7a877e; font-size: 14rpx; }.plan-facts text:last-child { font-size: 18rpx; font-weight: 660; }.milestone { display: flex; margin-top: 20rpx; padding: 20rpx; flex-direction: column; gap: 8rpx; border-radius: 19rpx; background: #172019; color: #fff; }.milestone text:first-child { color: #98a69a; font-size: 14rpx; }.milestone text:last-child { font-size: 18rpx; line-height: 1.55; }
.week-plan { margin-top: 21rpx; }.week-plan-head { display: flex; align-items: flex-end; justify-content: space-between; }.week-plan-head > view { display: flex; flex-direction: column; gap: 5rpx; }.week-plan-head > view text:first-child { font-size: 20rpx; font-weight: 700; }.week-plan-head > view text:last-child { color: #7b877f; font-size: 14rpx; }.week-plan-head > button { color: #536b57; font-size: 16rpx; }.week-action { display: flex; align-items: center; gap: 12rpx; padding: 17rpx 0; border-top: 1rpx solid #e8ece6; }.week-action:first-of-type { margin-top: 13rpx; }.action-check { display: flex; width: 34rpx; height: 34rpx; flex: 0 0 34rpx; align-items: center; justify-content: center; border: 1rpx solid #94a097; border-radius: 50%; font-size: 18rpx; }.week-action.done .action-check { border-color: #55705a; background: #55705a; color: #fff; }.action-copy { display: flex; min-width: 0; flex: 1; flex-direction: column; align-items: flex-start; gap: 4rpx; text-align: left; }.action-copy text:first-child { font-size: 18rpx; }.action-copy text:last-child { color: #7a877f; font-size: 13rpx; }.week-action.done .action-copy text:first-child { color: #88918a; text-decoration: line-through; }.action-todo { padding: 10rpx 13rpx; border-radius: 999rpx; background: #edf2e9; color: #617064; font-size: 13rpx; }.week-empty { display: flex; margin-top: 15rpx; padding: 19rpx; flex-direction: column; gap: 12rpx; border-radius: 17rpx; background: #f3f6f1; color: #6d796f; font-size: 16rpx; line-height: 1.5; }.week-empty button { align-self: flex-start; color: #426048; font-weight: 700; }
.next-step { display: flex; margin-top: 21rpx; padding: 21rpx; flex-direction: column; gap: 8rpx; border-radius: 21rpx; background: #e5ecd3; }.next-step > text:first-child { color: #6f7b64; font-size: 14rpx; }.next-step > text:nth-child(2) { font-size: 19rpx; line-height: 1.5; }.next-step > view { display: flex; gap: 10rpx; margin-top: 8rpx; }.next-step button { padding: 12rpx 16rpx; border-radius: 999rpx; background: rgba(255,255,255,.65); color: #52624e; font-size: 14rpx; }.stop-list { display: flex; margin-top: 18rpx; flex-direction: column; gap: 7rpx; color: #6d6459; font-size: 16rpx; }.stop-list text:first-child { color: #4f493f; font-weight: 700; }.bottleneck-trigger { width: 100%; margin-top: 22rpx; padding: 17rpx; border-top: 1rpx solid #e5eae3; color: #66736a; font-size: 15rpx; text-align: left; }
.linked-action, .validation-guidance, .confirmation-warning { display: block; margin-top: 18rpx; padding: 17rpx 19rpx; border-radius: 17rpx; background: #eef3ea; color: #657268; font-size: 16rpx; line-height: 1.55; }.confirm-ledger { display: flex; margin-top: 22rpx; padding: 19rpx 0; border-top: 1rpx solid #e4e9e2; border-bottom: 1rpx solid #e4e9e2; }.confirm-ledger view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 6rpx; }.confirm-ledger view + view { padding-left: 15rpx; border-left: 1rpx solid #e4e9e2; }.confirm-ledger text:first-child { color: #7a867e; font-size: 13rpx; }.confirm-ledger text:last-child { font-size: 19rpx; font-weight: 700; }.confirmation-warning { background: #f4efe2; color: #736950; }
.validation-options { display: flex; margin-top: 19rpx; flex-direction: column; gap: 10rpx; }.validation-options button { display: flex; padding: 18rpx 19rpx; flex-direction: column; align-items: flex-start; gap: 5rpx; border: 1rpx solid #e0e6de; border-radius: 17rpx; text-align: left; }.validation-options button.active { border-color: #536c58; background: #eaf1e5; }.validation-options text:first-child { font-size: 18rpx; font-weight: 700; }.validation-options text:last-child { color: #728076; font-size: 15rpx; line-height: 1.45; }.blocker-insight { display: flex; margin-top: 20rpx; padding: 21rpx; flex-direction: column; gap: 8rpx; border-radius: 19rpx; background: #edf2e9; color: #526055; font-size: 17rpx; line-height: 1.55; }.blocker-insight > text:nth-child(odd) { color: #738079; font-size: 13rpx; font-weight: 700; }.blocker-insight button { margin-top: 9rpx; color: #3f5b45; font-weight: 700; text-align: left; }
.diary-feedback, .result-row { padding: 20rpx 0; border-top: 1rpx solid #e8ece6; }.diary-feedback:first-of-type, .result-row:first-of-type { margin-top: 14rpx; }.diary-feedback > text { display: block; }.diary-feedback > text:first-child { color: #77847b; font-size: 14rpx; }.diary-feedback > text:nth-child(2) { margin-top: 9rpx; font-size: 18rpx; line-height: 1.55; }.diary-feedback > view { display: flex; gap: 15rpx; margin-top: 12rpx; }.diary-feedback button { color: #4f6954; font-size: 14rpx; }.review-list { display: flex; margin-top: 18rpx; flex-direction: column; gap: 7rpx; color: #5e6b61; font-size: 16rpx; }.review-list > text:first-child { color: #3f4d43; font-weight: 700; }
.result-row > view:first-child { display: flex; justify-content: space-between; gap: 14rpx; }.result-row > view:first-child text:first-child { font-size: 17rpx; font-weight: 700; }.result-row > view:first-child text:last-child { color: #879189; font-size: 13rpx; }.result-row > text { display: block; margin-top: 8rpx; color: #566359; font-size: 17rpx; line-height: 1.55; }.result-meta { display: flex; gap: 9rpx; margin-top: 11rpx; flex-wrap: wrap; }.result-meta text { padding: 6rpx 10rpx; border-radius: 999rpx; background: #edf2e9; color: #637067; font-size: 13rpx; }
.secondary-links { margin-top: 25rpx; overflow: hidden; border-radius: 29rpx; background: rgba(255,255,255,.72); }.secondary-links > button { display: flex; width: 100%; align-items: center; justify-content: space-between; gap: 18rpx; padding: 23rpx 27rpx; border-top: 1rpx solid rgba(23,32,25,.07); text-align: left; }.secondary-links > button:first-child { border-top: 0; }.secondary-links > button > view { display: flex; min-width: 0; flex: 1; flex-direction: column; gap: 5rpx; }.secondary-links > button > view text:first-child { font-size: 19rpx; font-weight: 680; }.secondary-links > button > view text:last-child { color: #758078; font-size: 15rpx; line-height: 1.45; }.secondary-links > button > text { color: #748078; font-size: 29rpx; }.privacy-note { display: flex; align-items: flex-start; gap: 12rpx; margin-top: 24rpx; padding: 18rpx 21rpx; border-radius: 20rpx; background: #e1ead9; color: #5a685e; font-size: 15rpx; line-height: 1.55; }.privacy-note view { width: 8rpx; height: 8rpx; margin-top: 7rpx; flex: 0 0 8rpx; border-radius: 50%; background: #56705b; }

/* Mobile-first readability: one decision per screen, details only on demand. */
input, textarea { font-size: 30rpx; }
.page-shell { padding: 24rpx 28rpx 150rpx; }
.topbar-kicker, .eyebrow { font-size: 22rpx; letter-spacing: 1.4rpx; }
.topbar-title { font-size: 40rpx; }
.portfolio-hero { padding: 34rpx 31rpx; border-radius: 32rpx; }
.portfolio-title { margin-top: 15rpx; font-size: 43rpx; line-height: 1.28; }
.portfolio-copy { margin-top: 15rpx; font-size: 29rpx; line-height: 1.58; }
.hero-status { display: flex; gap: 14rpx; margin-top: 24rpx; flex-wrap: wrap; }.hero-status text { padding: 11rpx 16rpx; border-radius: 999rpx; background: rgba(255,255,255,.1); color: #d6dfd7; font-size: 25rpx; }
.hero-action { min-height: 88rpx; padding: 22rpx 27rpx; font-size: 29rpx; }
.catalog-panel, .editor-panel, .plan-card, .feedback-section, .recent-section { padding: 28rpx; border-radius: 28rpx; }
.panel-heading > view > text:last-child, .section-intro > view > text:last-child { font-size: 37rpx; line-height: 1.35; }
.panel-heading > button { display: flex; min-width: 70rpx; min-height: 70rpx; align-items: center; justify-content: center; font-size: 42rpx; }
.section-intro { align-items: center; }.section-intro > button { min-height: 70rpx; font-size: 27rpx; }
.catalog-intro { margin-top: 18rpx; font-size: 29rpx; line-height: 1.55; }
.catalog-tabs { gap: 7rpx; padding: 7rpx; }.catalog-tabs button { min-height: 82rpx; padding: 10rpx; font-size: 26rpx; line-height: 1.3; }.catalog-tabs text { font-size: 22rpx; }
.protection-note { padding: 20rpx; font-size: 27rpx; }
.archetype-card { min-height: 88rpx; align-items: center; padding: 20rpx 8rpx; }.archetype-number { font-size: 23rpx; }.archetype-copy text:first-child { font-size: 31rpx; }.archetype-copy text:last-child { font-size: 27rpx; }.archetype-arrow { font-size: 38rpx; }
.catalog-more, .detail-toggle, .plan-detail-toggle, .activity-toggle { display: flex; width: 100%; min-height: 82rpx; align-items: center; justify-content: space-between; margin-top: 12rpx; padding: 16rpx 5rpx; color: #526558; font-size: 28rpx; text-align: left; }.catalog-more { justify-content: center; border-top: 1rpx solid #e6ebe4; }
.archetype-detail { padding: 29rpx; }.detail-head > view text:first-child, .detail-head > text { font-size: 22rpx; }.detail-head > view text:last-child { font-size: 37rpx; }.loop-statement text:first-child, .fit-grid view text:first-child, .example-list > text:first-child { font-size: 23rpx; }.loop-statement text:last-child { font-size: 30rpx; line-height: 1.55; }.fit-grid view text:last-child, .default-measures text:last-child, .example-list text:not(:first-child) { font-size: 27rpx; }.default-measures text:first-child { font-size: 22rpx; }.detail-toggle.dark { color: #dbe5dc; border-top: 1rpx solid rgba(255,255,255,.12); }
.chosen-archetype > text { font-size: 22rpx; }.chosen-archetype > view text:first-child { font-size: 31rpx; }.chosen-archetype > view text:last-child { font-size: 27rpx; }
.editor-intro text:first-child, .finance-boundary text:first-child { font-size: 30rpx; }.editor-intro text:last-child, .finance-boundary text:last-child { font-size: 27rpx; }
.editor-field > text, .metric-editor > view > text { font-size: 28rpx; }.editor-field input, .editor-field textarea, .metric-editor input { min-height: 88rpx; padding: 22rpx; font-size: 30rpx; }.editor-field textarea { min-height: 130rpx; }
.finance-step-progress { display: flex; justify-content: space-between; margin-top: 25rpx; padding: 0 4rpx; }.finance-step-progress > view { display: flex; width: 25%; align-items: center; flex-direction: column; gap: 8rpx; color: #8a938c; }.finance-step-progress > view > text { display: flex; width: 50rpx; height: 50rpx; align-items: center; justify-content: center; border-radius: 50%; background: #e8ede5; font-size: 25rpx; font-weight: 700; }.finance-step-progress > view > small { font-size: 22rpx; }.finance-step-progress > view.active > text, .finance-step-progress > view.done > text { background: #172019; color: #fff; }.finance-step-progress > view.active > small { color: #172019; font-weight: 700; }
.finance-step-title { display: flex; margin-top: 28rpx; flex-direction: column; gap: 8rpx; }.finance-step-title > text { color: #738078; font-size: 23rpx; font-weight: 700; }.finance-step-title strong { font-family: Georgia, 'Songti SC', serif; font-size: 38rpx; line-height: 1.35; }.finance-step-title small { color: #6c786f; font-size: 27rpx; line-height: 1.5; }
.finance-choice { gap: 12rpx; margin-top: 18rpx; }.finance-choice > text { font-size: 28rpx; }.finance-choice button { min-height: 78rpx; padding: 17rpx 21rpx; font-size: 27rpx; }
.planned-not-held { padding: 18rpx; font-size: 26rpx; }.finance-plan-summary > text, .finance-plan-summary small { font-size: 24rpx; }.finance-plan-summary strong { font-size: 30rpx; }
.boundary-consent label { gap: 16rpx; font-size: 27rpx; line-height: 1.55; }.boundary-consent checkbox { transform: scale(1); }
.finance-step-nav { display: flex; gap: 14rpx; margin-top: 23rpx; }.finance-step-nav button { display: flex; min-height: 88rpx; flex: 1; align-items: center; justify-content: center; border: 1rpx solid #ced8cc; border-radius: 999rpx; color: #55645a; font-size: 29rpx; font-weight: 700; }.finance-step-nav button.next { border-color: #172019; background: #172019; color: #fff; }
.primary-action { min-height: 92rpx; font-size: 30rpx; }
.two-column, .metric-editor, .metric-pair { flex-direction: column; }.metric-editor input { min-height: 84rpx; }
.system-setup > text, .system-setup > view text:first-child { font-size: 23rpx; }.system-setup > view text:last-child { font-size: 27rpx; }.advanced-toggle { min-height: 80rpx; font-size: 27rpx; }.validation-notice text:first-child { font-size: 29rpx; }.validation-notice text:last-child { font-size: 27rpx; }
.plan-head > view:first-child text:first-child { font-size: 23rpx; }.plan-head > view:first-child text:last-child { font-size: 38rpx; }.plan-head-actions .more-action { min-width: 64rpx; min-height: 64rpx; font-size: 28rpx; }.validation-row > text, .validation-row > button { font-size: 23rpx; }.plan-outcome { display: -webkit-box; overflow: hidden; font-size: 29rpx; line-height: 1.55; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }
.plan-focus { display: flex; margin-top: 21rpx; padding: 21rpx; flex-direction: column; gap: 7rpx; border-radius: 20rpx; background: #eef3eb; }.plan-focus text:first-child { color: #758078; font-size: 23rpx; }.plan-focus text:last-child { font-size: 29rpx; line-height: 1.5; }
.finance-open { min-height: 90rpx; padding: 0 25rpx; font-size: 30rpx; }.next-step.compact { margin-top: 21rpx; }.next-step > text:first-child { font-size: 23rpx; }.next-step > text:nth-child(2) { font-size: 30rpx; }.next-step button { min-height: 70rpx; padding: 16rpx 21rpx; font-size: 27rpx; }
.plan-detail-toggle { border-top: 1rpx solid #e3e9e1; }.plan-details { margin-top: 5rpx; }.compound-loop > view { grid-template-columns: 190rpx 1fr; }.compound-loop text:first-child { font-size: 23rpx; }.compound-loop text:last-child { font-size: 28rpx; }.metric-pair > view > text:first-child, .metric-pair small { font-size: 23rpx; }.metric-pair > view > text:nth-child(2) { font-size: 27rpx; }.metric-pair strong { font-size: 36rpx; }.plan-facts { flex-direction: column; gap: 18rpx; }.plan-facts view + view { padding-left: 0; border-left: 0; }.plan-facts text:first-child { font-size: 23rpx; }.plan-facts text:last-child, .milestone text:last-child { font-size: 28rpx; }.milestone text:first-child { font-size: 23rpx; }.week-plan-head > view text:first-child { font-size: 31rpx; }.week-plan-head > view text:last-child, .week-plan-head > button { font-size: 25rpx; }.week-action { min-height: 86rpx; }.action-copy text:first-child { font-size: 29rpx; }.action-copy text:last-child, .action-todo { font-size: 23rpx; }.week-empty, .stop-list, .bottleneck-trigger { font-size: 27rpx; }
.activity-toggle { margin-top: 27rpx; padding: 22rpx 25rpx; border-radius: 24rpx; background: rgba(255,255,255,.75); }.activity-toggle > view { display: flex; flex-direction: column; gap: 6rpx; }.activity-toggle > view text:first-child { font-size: 30rpx; font-weight: 700; }.activity-toggle > view text:last-child { color: #738078; font-size: 25rpx; }.activity-toggle > text { font-size: 35rpx; }
.secondary-links > button { min-height: 100rpx; }.secondary-links > button > view text:first-child { font-size: 30rpx; }.secondary-links > button > view text:last-child, .privacy-note { font-size: 26rpx; }
/* #ifdef H5 */
@media (min-width: 980px) { .compound-page { box-sizing: border-box; padding-left: 96px; }.status-bar { display: none; }.page-shell { max-width: 960px; margin: 0 auto; padding: 55px 42px 100px; }.portfolio-hero { padding: 50px; }.portfolio-title { max-width: 720px; font-size: 42px; }.archetype-grid { display: grid; grid-template-columns: 1fr 1fr; column-gap: 22px; }.archetype-card:nth-child(2) { border-top: 0; }.plan-card, .catalog-panel, .editor-panel { padding: 34px; }.metric-editor > view { min-width: 0; } }
/* #endif */
</style>
